import { PAGE_URLS } from "@/constants/urls";

export const UNPROTECTED_ROUTES = [PAGE_URLS.LOGIN, PAGE_URLS.SIGNUP, PAGE_URLS.HOME, PAGE_URLS.EACH_BOOK_PATH, PAGE_URLS.LIVE];
export const AUTH_ROUTES = [PAGE_URLS.LOGIN, PAGE_URLS.SIGNUP]